server:
  port: ":3000"
  environment: "local"
  security:
    rateLimit:
      qps: 100
    cors:
      allowedOrigins:
        - "http://localhost:3000"
        - "http://127.0.0.1:3000"
        - "http://localhost:8080"
        - "http://127.0.0.1:8080"
        - "http://localhost:8081"
        - "http://127.0.0.1:8081"
    csrf:
      enabled: false

service:
  name: "api-gateway"

log:
  level: "debug"
  format: "json"

newrelic:
  enabled: false
  appName: "api-gateway"
  licenseKey: ""
  distributedTracer: true

notification:
  slack:
    webhookURL: ""
    errorChannelID: ""

google:
  clientID: ""

downstream:
  baseURL: "http://localhost:8080"
